
export type Question = {
    id: string;
    module: string;
    text: string;
    options: { id: 'a' | 'b' | 'c' | 'd'; text: string }[];
    correctAnswer: 'a' | 'b' | 'c' | 'd';
    difficulty: 'easy' | 'medium' | 'hard';
    points: 1 | 2 | 5;
};

export const quizModules = [
  { topic: 'Eyelids & Adnexa', time: 5 * 60, totalPoints: 18, timeBonus: 2 },
  { topic: 'Conjunctiva & Sclera', time: 6 * 60, totalPoints: 17, timeBonus: 2 },
  { topic: 'Cornea', time: 7 * 60, totalPoints: 20, timeBonus: 2 },
  { topic: 'Anterior Chamber & Aqueous Humor', time: 6 * 60, totalPoints: 16, timeBonus: 1 },
  { topic: 'Iris & Pupil', time: 6 * 60, totalPoints: 15, timeBonus: 1 },
  { topic: 'Crystalline Lens & Accommodation', time: 7 * 60, totalPoints: 19, timeBonus: 2 },
  { topic: 'Vitreous Body', time: 5 * 60, totalPoints: 15, timeBonus: 1 },
  { topic: 'Retina', time: 9 * 60, totalPoints: 24, timeBonus: 2 },
  { topic: 'Optic Nerve & Pathways', time: 9 * 60, totalPoints: 24, timeBonus: 2 },
  { topic: 'Extraocular Muscles & Ocular Motility', time: 5 * 60, totalPoints: 16, timeBonus: 2 },
];

export const questions: Question[] = [
    // Module 1: Eyelids & Adnexa (Total Points: 18)
    {
        id: 'm1q1',
        module: 'Eyelids & Adnexa',
        text: 'Which gland is responsible for the oily (lipid) layer of the tear film, preventing rapid evaporation?',
        options: [
            { id: 'a', text: 'Lacrimal Gland' },
            { id: 'b', text: 'Glands of Krause' },
            { id: 'c', text: 'Meibomian Gland' },
            { id: 'd', text: 'Glands of Wolfring' },
        ],
        correctAnswer: 'c',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm1q2',
        module: 'Eyelids & Adnexa',
        text: "Bell's phenomenon, the upward and outward rotation of the eyeball on attempted forceful closure of the eyelids, is a protective reflex. Which cranial nerve mediates this motor response?",
        options: [
            { id: 'a', text: 'CN III (Oculomotor)' },
            { id: 'b', text: 'CN V (Trigeminal)' },
            { id: 'c', text: 'CN IV (Trochlear)' },
            { id: 'd', text: 'CN VII (Facial)' },
        ],
        correctAnswer: 'd',
        difficulty: 'medium',
        points: 2,
    },
     {
        id: 'm1q3',
        module: 'Eyelids & Adnexa',
        text: 'Ptosis, the drooping of the upper eyelid, can be caused by a dysfunction of which two muscles?',
        options: [
            { id: 'a', text: 'Orbicularis Oculi and Frontalis' },
            { id: 'b', text: 'Levator Palpebrae Superioris and Müller\'s muscle' },
            { id: 'c', text: 'Superior Rectus and Superior Oblique' },
            { id: 'd', text: 'Corrugator and Procerus' },
        ],
        correctAnswer: 'b',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm1q4',
        module: 'Eyelids & Adnexa',
        text: 'A 60-year-old patient presents with chronic eye irritation, a foreign body sensation, and lashes that are visibly turned inward and rubbing against the cornea. What is the most specific diagnosis for this condition?',
        options: [
            { id: 'a', text: 'Ectropion' },
            { id: 'b', text: 'Trichiasis' },
            { id: 'c', text: 'Entropion' },
            { id: 'd', text: 'Blepharitis' },
        ],
        correctAnswer: 'c',
        difficulty: 'hard',
        points: 5,
    },
     {
        id: 'm1q5',
        module: 'Eyelids & Adnexa',
        text: 'A chalazion is a sterile, granulomatous inflammation resulting from a blockage of which specific gland?',
        options: [
            { id: 'a', text: 'Gland of Zeis' },
            { id: 'b', text: 'Gland of Moll' },
            { id: 'c', text: 'Meibomian Gland' },
            { id: 'd', text: 'Accessory Lacrimal Gland' },
        ],
        correctAnswer: 'c',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm1q6',
        module: 'Eyelids & Adnexa',
        text: 'The palpebral conjunctiva is the vascular mucous membrane that covers which surface?',
        options: [
            { id: 'a', text: 'The anterior surface of the sclera' },
            { id: 'b', text: 'The posterior surface of the eyelids' },
            { id: 'c', text: 'The cornea' },
            { id: 'd', text: 'The junction between the cornea and sclera' },
        ],
        correctAnswer: 'b',
        difficulty: 'easy',
        points: 1,
    },
     {
        id: 'm1q7',
        module: 'Eyelids & Adnexa',
        text: 'What is the correct sequence for tear drainage through the lacrimal system?',
        options: [
            { id: 'a', text: 'Canaliculi -> Puncta -> Lacrimal Sac -> Nasolacrimal Duct' },
            { id: 'b', text: 'Puncta -> Lacrimal Sac -> Canaliculi -> Nasolacrimal Duct' },
            { id: 'c', text: 'Puncta -> Canaliculi -> Lacrimal Sac -> Nasolacrimal Duct' },
            { id: 'd', text: 'Lacrimal Sac -> Puncta -> Canaliculi -> Nasolacrimal Duct' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm1q8',
        module: 'Eyelids & Adnexa',
        text: 'An external hordeolum (stye) is an acute staphylococcal infection typically found in a gland of Zeis or Moll. Where are these glands located?',
        options: [
            { id: 'a', text: 'Within the tarsal plate' },
            { id: 'b', text: 'At the base of the eyelashes' },
            { id: 'c', text: 'In the conjunctival fornix' },
            { id: 'd', text: 'Near the caruncle' },
        ],
        correctAnswer: 'b',
        difficulty: 'easy',
        points: 1,
    },
     {
        id: 'm1q9',
        module: 'Eyelids & Adnexa',
        text: 'The "gray line" of the eyelid margin is an important surgical landmark because it represents the location of the:',
        options: [
            { id: 'a', text: 'Meibomian gland orifices' },
            { id: 'b', text: 'Insertion of the levator aponeurosis' },
            { id: 'c', text: 'Muscle of Riolan (the most superficial part of the orbicularis oculi)' },
            { id: 'd', text: 'None of the above' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm1q10',
        module: 'Eyelids & Adnexa',
        text: 'Which muscle is primarily responsible for the forceful closure (winking or squeezing) of the eyelids?',
        options: [
            { id: 'a', text: 'Levator palpebrae superioris' },
            { id: 'b', text: 'Müller\'s muscle' },
            { id: 'c', text: 'Frontalis muscle' },
            { id: 'd', text: 'Orbicularis oculi' },
        ],
        correctAnswer: 'd',
        difficulty: 'easy',
        points: 1,
    },

    // Module 2: Conjunctiva & Sclera (Total Points: 17)
    {
        id: 'm2q1',
        module: 'Conjunctiva & Sclera',
        text: 'Which cells, found within the conjunctival epithelium, are responsible for producing the mucin layer of the tear film?',
        options: [
            { id: 'a', text: 'Epithelial cells' },
            { id: 'b', text: 'Goblet cells' },
            { id: 'c', text: 'Melanocytes' },
            { id: 'd', text: 'Langerhans cells' },
        ],
        correctAnswer: 'b',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm2q2',
        module: 'Conjunctiva & Sclera',
        text: 'A pinguecula is a common degenerative condition of the conjunctiva, presenting as a yellowish, slightly raised elastotic lesion. Where is it most typically found?',
        options: [
            { id: 'a', text: 'Superior bulbar conjunctiva, protected by the eyelid' },
            { id: 'b', text: 'Inferior palpebral conjunctiva' },
            { id: 'c', text: 'In the interpalpebral fissure, most often nasally' },
            { id: 'd', text: 'In the forniceal conjunctiva' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
     {
        id: 'm2q3',
        module: 'Conjunctiva & Sclera',
        text: 'The sclera provides the structural "white" of the eye. It is anatomically thinnest at which point?',
        options: [
            { id: 'a', text: 'At the limbus' },
            { id: 'b', text: 'At the posterior pole, surrounding the optic nerve' },
            { id: 'c', text: 'Just behind the insertions of the extraocular rectus muscles' },
            { id: 'd', text: 'At the equator of the globe' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm2q4',
        module: 'Conjunctiva & Sclera',
        text: 'A 30-year-old patient presents with sectoral redness and mild-to-moderate discomfort. You instill 2.5% phenylephrine drops, and the superficial redness blanches significantly, revealing deep, non-moving, tortuous vessels underneath. What is the most likely diagnosis?',
        options: [
            { id: 'a', text: 'Nodular Scleritis' },
            { id: 'b', text: 'Episcleritis' },
            { id: 'c', text: 'Allergic Conjunctivitis' },
            { id: 'd', text: 'This test is inconclusive' },
        ],
        correctAnswer: 'a',
        difficulty: 'hard',
        points: 5,
    },
     {
        id: 'm2q5',
        module: 'Conjunctiva & Sclera',
        text: 'The palisades of Vogt, a critical source of corneal epithelial stem cells for continuous regeneration, are located in which anatomical region?',
        options: [
            { id: 'a', text: 'The bulbar conjunctiva' },
            { id: 'b', text: 'The tarsal conjunctiva' },
            { id: 'c', text: 'The limbus' },
            { id: 'd', text: 'The fornix' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm2q6',
        module: 'Conjunctiva & Sclera',
        text: 'Giant papillary conjunctivitis (GPC) is a Type I and Type IV hypersensitivity reaction most commonly associated with:',
        options: [
            { id: 'a', text: 'Viral infections' },
            { id: 'b', text: 'Bacterial infections' },
            { id: 'c', text: 'Chronic mechanical irritation from contact lens wear' },
            { id: 'd', text: 'Seasonal allergies' },
        ],
        correctAnswer: 'c',
        difficulty: 'easy',
        points: 1,
    },
     {
        id: 'm2q7',
        module: 'Conjunctiva & Sclera',
        text: 'What is the primary structural protein that gives the sclera its tensile strength and opaque white color?',
        options: [
            { id: 'a', text: 'Elastin' },
            { id: 'b', text: 'Keratin' },
            { id: 'c', text: 'Type I Collagen' },
            { id: 'd', text: 'Fibronectin' },
        ],
        correctAnswer: 'c',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm2q8',
        module: 'Conjunctiva & Sclera',
        text: 'The lamina fusca is the innermost, pigmented layer of the sclera, adjacent to the choroid. Its color comes from a high concentration of:',
        options: [
            { id: 'a', text: 'Fibroblasts' },
            { id: 'b', text: 'Melanocytes' },
            { id: 'c', text: 'Goblet cells' },
            { id: 'd', text: 'None of the above' },
        ],
        correctAnswer: 'b',
        difficulty: 'medium',
        points: 2,
    },
     {
        id: 'm2q9',
        module: 'Conjunctiva & Sclera',
        text: 'Which type of conjunctival injection is characterized by deep, non-moving, violaceous vessels and is a hallmark of serious intraocular inflammation like iridocyclitis or scleritis?',
        options: [
            { id: 'a', text: 'Papillary injection' },
            { id: 'b', text: 'Follicular injection' },
            { id: 'c', text: 'Ciliary flush (circumcorneal injection)' },
            { id: 'd', text: 'Diffuse injection from simple conjunctivitis' },
        ],
        correctAnswer: 'c',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm2q10',
        module: 'Conjunctiva & Sclera',
        text: 'A pterygium is a triangular growth of fibrovascular tissue that invades the cornea. It is strongly associated with which environmental factor?',
        options: [
            { id: 'a', text: 'Low humidity environments' },
            { id: 'b', text: 'High altitude' },
            { id: 'c', text: 'Chronic exposure to ultraviolet (UV) radiation' },
            { id: 'd', text: 'Air pollution' },
        ],
        correctAnswer: 'c',
        difficulty: 'easy',
        points: 1,
    },

    // Module 3: Cornea (Total Points: 20)
    {
        id: 'm3q1',
        module: 'Cornea',
        text: 'Which corneal layer is a single cell thick and actively maintains corneal deturgescence (relative dehydration) via the Na+/K+ ATPase pump?',
        options: [
            { id: 'a', text: 'Epithelium' },
            { id: 'b', text: 'Bowman\'s Layer' },
            { id: 'c', text: 'Stroma' },
            { id: 'd', text: 'Endothelium' },
        ],
        correctAnswer: 'd',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm3q2',
        module: 'Cornea',
        text: 'The majority of the cornea\'s total refractive power (~43D) comes from which interface?',
        options: [
            { id: 'a', text: 'The endothelium-aqueous humor interface' },
            { id: 'b', text: 'The anterior corneal surface (air-tear film interface)' },
            { id: 'c', text: 'The stroma' },
            { id: 'd', text: 'The posterior corneal surface (stroma-endothelium interface)' },
        ],
        correctAnswer: 'b',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm3q3',
        module: 'Cornea',
        text: 'A 65-year-old patient reports hazy, blurry vision that is worst upon waking and gradually improves throughout the day. Slit lamp exam reveals corneal guttae and mild stromal edema. This clinical picture is most characteristic of:',
        options: [
            { id: 'a', text: 'Keratoconus' },
            { id: 'b', text: 'Fuchs\' Endothelial Dystrophy' },
            { id: 'c', text: 'Recurrent Corneal Erosion' },
            { id: 'd', text: 'Map-Dot-Fingerprint Dystrophy' },
        ],
        correctAnswer: 'b',
        difficulty: 'hard',
        points: 5,
    },
    {
        id: 'm3q4',
        module: 'Cornea',
        text: 'A branching, linear ulcer visualized with fluorescein stain is the pathognomonic sign of which type of infectious keratitis?',
        options: [
            { id: 'a', text: 'Pseudomonas aeruginosa keratitis' },
            { id: 'b', text: 'Fungal keratitis' },
            { id: 'c', text: 'Herpes Simplex Virus (HSV) epithelial keratitis' },
            { id: 'd', text: 'Acanthamoeba keratitis' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm3q5',
        module: 'Cornea',
        text: 'What is the approximate average dioptric power of the human cornea?',
        options: [
            { id: 'a', text: '~23 D' },
            { id: 'b', text: '~33 D' },
            { id: 'c', text: '~43 D' },
            { id: 'd', text: '~58 D' },
        ],
        correctAnswer: 'c',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm3q6',
        module: 'Cornea',
        text: 'Which acellular corneal layer, if damaged, will form a scar and does not regenerate?',
        options: [
            { id: 'a', text: 'Epithelium' },
            { id: 'b', text: 'Bowman\'s Layer' },
            { id: 'c', text: 'Dua\'s Layer' },
            { id: 'd', text: 'Descemet\'s Membrane' },
        ],
        correctAnswer: 'b',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm3q7',
        module: 'Cornea',
        text: 'Under normal, eyes-open conditions, from where does the cornea receive the majority of its oxygen supply?',
        options: [
            { id: 'a', text: 'The limbal vasculature' },
            { id: 'b', text: 'The aqueous humor' },
            { id: 'c', text: 'The palpebral conjunctival vessels' },
            { id: 'd', text: 'Directly from the atmosphere via the tear film' },
        ],
        correctAnswer: 'd',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm3q8',
        module: 'Cornea',
        text: 'A "Whorl Keratopathy" (Cornea Verticillata), characterized by fine, golden-brown deposits in the basal corneal epithelium, is a well-known ocular side effect of which systemic medication?',
        options: [
            { id: 'a', text: 'Hydroxychloroquine' },
            { id: 'b', text: 'Amiodarone' },
            { id: 'c', text: 'Tamoxifen' },
            { id: 'd', text: 'All of the above' },
        ],
        correctAnswer: 'd',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm3q9',
        module: 'Cornea',
        text: 'Corneal endothelial cells are non-mitotic. What is the primary mechanism by which the endothelium compensates for cell loss?',
        options: [
            { id: 'a', text: 'Cell regeneration from limbal stem cells' },
            { id: 'b', text: 'Polymegathism (increase in cell size) and pleomorphism (change in cell shape)' },
            { id: 'c', text: 'Cell division (mitosis)' },
            { id: 'd', text: 'Recruitment of cells from the trabecular meshwork' },
        ],
        correctAnswer: 'b',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm3q10',
        module: 'Cornea',
        text: 'Corneal transparency is maintained by the precise, lattice-like arrangement of collagen fibrils in the stroma, as explained by which theory?',
        options: [
            { id: 'a', text: 'The Maurice theory of destructive interference' },
            { id: 'b', text: 'The Goldman theory of aqueous dynamics' },
            { id: 'c', text: 'The Helmholtz theory of accommodation' },
            { id: 'd', text: 'The Young-Helmholtz theory of color vision' },
        ],
        correctAnswer: 'a',
        difficulty: 'medium',
        points: 2,
    },
    
    // Module 4: Anterior Chamber & Aqueous Humor (Total Points: 16)
    { id: 'm4q1', module: 'Anterior Chamber & Aqueous Humor', text: 'Aqueous humor is actively secreted by which specific structure?', options: [{ id: 'a', text: 'Pigmented epithelium of the ciliary body' }, { id: 'b', text: 'Non-pigmented epithelium of the ciliary body' }, { id: 'c', text: 'Ciliary muscle' }, { id: 'd', text: 'Iris stroma' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm4q2', module: 'Anterior Chamber & Aqueous Humor', text: 'The conventional (trabecular) pathway accounts for approximately 80-90% of aqueous humor outflow. What is the correct sequence of this pathway?', options: [{ id: 'a', text: 'Uveoscleral pathway -> Suprachoroidal space' }, { id: 'b', text: 'Trabecular meshwork -> Schlemm\'s canal -> Episcleral veins' }, { id: 'c', text: 'Iris root -> Suprachoroidal space' }, { id: 'd', text: 'Schlemm\'s canal -> Trabecular meshwork -> Episcleral veins' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm4q3', module: 'Anterior Chamber & Aqueous Humor', text: 'Hyphema, a medical emergency, is defined as the presence of what in the anterior chamber?', options: [{ id: 'a', text: 'Pus (hypopyon)' },{ id: 'b', text: 'Red blood cells' },{ id: 'c', text: 'Lens particles (phacolytic uveitis)' },{ id: 'd', text: 'Pigment cells' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm4q4', module: 'Anterior Chamber & Aqueous Humor', text: 'A patient with open-angle glaucoma is prescribed latanoprost (a prostaglandin analog). What is the primary mechanism of action for this class of medication?', options: [{ id: 'a', text: 'Decreasing aqueous production' },{ id: 'b', text: 'Increasing outflow through the trabecular meshwork' },{ id: 'c', text: 'Increasing outflow through the uveoscleral (unconventional) pathway' },{ id: 'd', text: 'Causing miosis to stretch the trabecular meshwork' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm4q5', module: 'Anterior Chamber & Aqueous Humor', text: 'The normal depth of the central anterior chamber in a healthy adult eye is typically around:', options: [{ id: 'a', text: '1.5 mm' },{ id: 'b', text: '2.0 mm' },{ id: 'c', text: '3.0 - 3.5 mm' },{ id: 'd', text: '5.0 mm' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm4q6', module: 'Anterior Chamber & Aqueous Humor', text: 'Compared to blood plasma, aqueous humor has a significantly lower concentration of _____ and a higher concentration of _____.', options: [{ id: 'a', text: 'Ascorbate, Protein' },{ id: 'b', text: 'Protein, Ascorbate' },{ id: 'c', text: 'Glucose, Lactate' },{ id: 'd', text: 'Sodium, Potassium' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm4g7', module: 'Anterior Chamber & Aqueous Humor', text: 'The angle of the anterior chamber, critical for aqueous outflow, is the anatomical junction between the:', options: [{ id: 'a', text: 'Iris and Lens' },{ id: 'b', text: 'Cornea and Ciliary body' },{ id: 'c', text: 'Peripheral cornea and the root of the iris' },{ id: 'd', text: 'Lens and Sclera' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm4q8', module: 'Anterior Chamber & Aqueous Humor', text: 'Gonioscopy is a clinical technique specifically used to visualize the:', options: [{ id: 'a', text: 'Retinal periphery' },{ id: 'b', text: 'Optic nerve head' },{ id: 'c', text: 'Vitreous body' },{ id: 'd', text: 'Anterior chamber angle structures' }], correctAnswer: 'd', difficulty: 'easy', points: 1 },
    { id: 'm4q9', module: 'Anterior Chamber & Aqueous Humor', text: 'A Krukenberg spindle, a vertical line of pigment on the central corneal endothelium, is a classic sign of which condition?', options: [{ id: 'a', text: 'Uveitis' },{ id: 'b', text: 'Pigment dispersion syndrome' },{ id: 'c', text: 'Pseudoexfoliation syndrome' },{ id: 'd', text: 'Fuchs\' dystrophy' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm4q10', module: 'Anterior Chamber & Aqueous Humor', text: 'Which medication class reduces aqueous production by inhibiting the enzyme responsible for bicarbonate formation in the ciliary epithelium?', options: [{ id: 'a', text: 'Beta-blockers (e.g., Timolol)' },{ id: 'b', text: 'Prostaglandin analogs (e.g., Latanoprost)' },{ id: 'c', text: 'Carbonic anhydrase inhibitors (e.g., Dorzolamide)' },{ id: 'd', text: 'Alpha-agonists (e.g., Brimonidine)' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },


    // Module 5: Iris & Pupil (Total Points: 15)
    { id: 'm5q1', module: 'Iris & Pupil', text: 'The color of the iris is primarily determined by the density and type of melanin within which two layers?', options: [{ id: 'a', text: 'Anterior border layer & Stroma' },{ id: 'b', text: 'Anterior and Posterior pigment epithelium' },{ id: 'c', text: 'Dilator muscle and Sphincter muscle' },{ id: 'd', text: 'Stroma and posterior pigment epithelium' }], correctAnswer: 'a', difficulty: 'medium', points: 2 },
    { id: 'm5q2', module: 'Iris & Pupil', text: 'Pupillary constriction (miosis) is controlled by which muscle and which branch of the autonomic nervous system?', options: [{ id: 'a', text: 'Dilator pupillae, Sympathetic' },{ id: 'b', text: 'Sphincter pupillae, Sympathetic' },{ id: 'c', text: 'Sphincter pupillae, Parasympathetic' },{ id: 'd', text: 'Dilator pupillae, Parasympathetic' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm5q3', module: 'Iris & Pupil', text: 'The term "anisocoria" refers to:', options: [{ id: 'a', 'text': 'An irregularly shaped pupil' },{ id: 'b', text: 'A detectable difference in pupil size between the two eyes' },{ id: 'c', text: 'A poor or sluggish pupillary reaction to light' },{ id: 'd', text: 'Inflammation of the iris' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm5q4', module: 'Iris & Pupil', text: 'A patient presents with a left relative afferent pupillary defect (RAPD or Marcus Gunn pupil). During the swinging-flashlight test, when the light is swung from the healthy right eye to the affected left eye, what will the left pupil do?', options: [{ id: 'a', text: 'Constrict further' },{ id: 'b', text: 'Remain unchanged in size' },{ id: 'c', text: 'Dilate paradoxically' },{ id: 'd', text: 'Constrict and then immediately dilate (hippus)' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm5q5', module: 'Iris & Pupil', text: 'The pharmacologic dilation of the pupil, often for diagnostic examination, is called:', options: [{ id: 'a', text: 'Miosis' },{ id: 'b', text: 'Mydriasis' },{ id: 'c', text: 'Cycloplegia' },{ id: 'd', text: 'Anisocoria' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm5q6', module: 'Iris & Pupil', text: 'The efferent (motor) pathway for the pupillary light reflex travels from the Edinger-Westphal nucleus along which cranial nerve?', options: [{ id: 'a', text: 'Optic nerve (CN II)' },{ id: 'b', text: 'Oculomotor nerve (CN III)' },{ id: 'c', text: 'Trigeminal nerve (CN V)' },{ id: 'd', text: 'Abducens nerve (CN VI)' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm5q7', module: 'Iris & Pupil', text: 'The iris collarette is an anatomical landmark that divides the iris into which two zones?', options: [{ id: 'a', text: 'The anterior and posterior zones' },{ id: 'b', text: 'The pupillary zone and the ciliary zone' },{ id: 'c', text: 'The stromal zone and the epithelial zone' },{ id: 'd', text: 'The sphincter zone and the dilator zone' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm5q8', module: 'Iris & Pupil', text: 'Which condition is specifically defined by inflammation of both the iris and the ciliary body?', options: [{ id: 'a', text: 'Iritis' },{ id: 'b', text: 'Iridocyclitis' },{ id: 'c', text: 'Kerato-uveitis' },{ id: 'd', text: 'Panuveitis' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm5q9', module: 'Iris & Pupil', text: 'In Horner\'s Syndrome, the classic triad of signs is ptosis, miosis, and:', options: [{ id: 'a', text: 'Mydriasis (dilation)' },{ id: 'b', text: 'Anhidrosis (decreased sweating)' },{ id: 'c', text: 'Proptosis (bulging eye)' },{ id: 'd', text: 'Lagophthalmos (inability to close the eyelid)' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm5q10', module: 'Iris & Pupil', text: 'The near reflex triad consists of which three synchronized actions?', options: [{ id: 'a', text: 'Pupil constriction, accommodation, and divergence' },{ id: 'b', text: 'Pupil dilation, lens thinning, and convergence' },{ id: 'c', text: 'Pupil constriction, accommodation, and convergence' },{ id: 'd', text: 'Pupil constriction, lens thinning, and divergence' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },

    // Module 6: Crystalline Lens & Accommodation (Total Points: 19)
    { id: 'm6q1', module: 'Crystalline Lens & Accommodation', text: 'What is the primary dynamic function of the crystalline lens?', options: [{ id: 'a', text: 'Absorbing UV light to protect the retina' },{ id: 'b', text: 'Providing a fixed refractive power' },{ id: 'c', text: 'Changing shape (accommodation) to focus on objects at various distances' },{ id: 'd', text: 'Producing aqueous humor' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm6q2', module: 'Crystalline Lens & Accommodation', text: 'A cataract is defined as any opacification of which ocular structure?', options: [{ id: 'a', text: 'Cornea' },{ id: 'b', 'text': 'Vitreous Humor' },{ id: 'c', text: 'Crystalline lens or its capsule' },{ id: 'd', text: 'Retina' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm6q3', module: 'Crystalline Lens & Accommodation', text: 'According to the Helmholtz theory of accommodation, what is the correct sequence of events when focusing on a near object?', options: [{ id: 'a', text: 'Ciliary muscle relaxes, zonules tighten, lens flattens' },{ id: 'b', text: 'Ciliary muscle contracts, zonules relax, lens becomes more convex' },{ id: 'c', text: 'Ciliary muscle contracts, zonules tighten, lens becomes more convex' },{ id: 'd', text: 'Ciliary muscle relaxes, zonules relax, lens flattens' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm6q4', module: 'Crystalline Lens & Accommodation', text: 'A young patient with uncontrolled Type 1 diabetes develops a rapidly progressing "snowflake" cataract. This is primarily due to osmotic over-hydration of the lens caused by the intracellular accumulation of:', options: [{ id: 'a', text: 'Lactic acid' },{ id: 'b', text: 'Sorbitol' },{ id: 'c', text: 'Advanced glycation end-products' },{ id: 'd', text: 'Free radicals' }], correctAnswer: 'b', difficulty: 'hard', points: 5 },
    { id: 'm6q5', module: 'Crystalline Lens & Accommodation', text: 'A posterior subcapsular cataract is most commonly associated with long-term systemic steroid use. What is its most characteristic visual symptom?', options: [{ id: 'a', text: 'Progressive myopic shift' },{ id: 'b', text: 'Disabling glare and difficulty reading in bright light' },{ id: 'c', text: 'Peripheral vision loss' },{ id: 'd', text: 'Monocular diplopia' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm6q6', module: 'Crystalline Lens & Accommodation', text: 'The lens capsule, the thickest basement membrane in the body, is primarily composed of what type of protein?', options: [{ id: 'a', text: 'Alpha-crystallins' },{ id: 'b', text: 'Elastin' },{ id: 'c', text: 'Type IV collagen' },{ id: 'd', text: 'Actin' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm6q7', module: 'Crystalline Lens & Accommodation', text: 'What is the clinical term for a partial or complete displacement of the crystalline lens from its normal position, often seen in genetic disorders like Marfan syndrome?', options: [{ id: 'a', text: 'Aphakia' },{ id: 'b', text: 'Pseudophakia' },{ id: 'c', text: 'Ectopia lentis' },{ id: 'd', text: 'Phacosclerosis' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm6q8', module: 'Crystalline Lens & Accommodation', text: 'Which type of senile cataract often causes a "myopic shift," sometimes referred to as "second sight," where a previously presbyopic patient can read again without glasses?', options: [{ id: 'a', text: 'Nuclear sclerotic' },{ id: 'b', text: 'Cortical' },{ id: 'c', text: 'Posterior subcapsular' },{ id: 'd', text: 'Traumatic' }], correctAnswer: 'a', difficulty: 'medium', points: 2 },
    { id: 'm6q9', module: 'Crystalline Lens & Accommodation', text: 'The amplitude of accommodation, which declines with age (presbyopia), is measured in:', options: [{ id: 'a', text: 'Millimeters (mm)' },{ id: 'b', text: 'Prism diopters (PD)' },{ id: 'c', text: 'Diopters (D)' },{ id: 'd', text: 'Degrees (°)' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm6q10', module: 'Crystalline Lens & Accommodation', text: 'Which soluble proteins, making up over 90% of the protein content in the lens, are crucial for its transparency and high refractive index?', options: [{ id: 'a', text: 'Albumins' },{ id: 'b', text: 'Globulins' },{ id: 'c', text: 'Crystallins (alpha, beta, gamma)' },{ id: 'd', text: 'Collagens' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },

    // Module 7: Vitreous Body (Total Points: 15)
    { id: 'm7q1', module: 'Vitreous Body', text: 'The vitreous body is an inert, transparent gel primarily composed of:', options: [{ id: 'a', text: '99% water and elastin fibers' },{ id: 'b', text: '99% water and high concentrations of hyaluronic acid' },{ id: 'c', text: '99% water, with a structural network of Type II collagen and hyaluronic acid' },{ id: 'd', text: 'Aqueous humor and albumin' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm7q2', module: 'Vitreous Body', text: 'A posterior vitreous detachment (PVD) occurs when the posterior vitreous cortex separates from which specific retinal layer?', options: [{ id: 'a', text: 'The posterior lens capsule' },{ id: 'b', text: 'The retinal pigment epithelium (RPE)' },{ id: 'c', text: 'The internal limiting membrane (ILM) of the retina' },{ id: 'd', text: 'The choroid' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm7q3', module: 'Vitreous Body', text: 'A 60-year-old patient reports a sudden onset of a single, large "cobweb" floater and flashes of light (photopsia) in their peripheral vision. This presentation is most classic for:', options: [{ id: 'a', text: 'Cataract progression' },{ id: 'b', text: 'A retinal detachment' },{ id: 'c', text: 'An acute posterior vitreous detachment (PVD)' },{ id: 'd', text: 'A migraine aura' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm7q4', module: 'Vitreous Body', text: 'What is the name of the ring-shaped floater, often reported by patients during a PVD, that represents the detached peripapillary glial tissue from around the optic nerve head?', options: [{ id: 'a', text: 'Muscae volitantes' },{ id: 'b', text: 'Vitreous syneresis' },{ id: 'c', text: 'Weiss ring' },{ id: 'd', text: 'Shafer\'s sign' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm7q5', module: 'Vitreous Body', text: 'Asteroid hyalosis is a condition characterized by numerous small, refractile, yellowish-white spherical deposits suspended within the vitreous. What are these deposits composed of?', options: [{ id: 'a', text: 'Cholesterol crystals' },{ id: 'b', text: 'Calcium-phosphate soaps' },{ id: 'c', text: 'Aggregated red blood cells' },{ id: 'd', text: 'Amyloid proteins' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm7q6', module: 'Vitreous Body', text: 'The strongest, most tenacious attachment of the vitreous to the surrounding ocular structures is at the:', options: [{ id: 'a', text: 'Optic disc margin' },{ id: 'b', text: 'Macula' },{ id: 'c', text: 'Vitreous base (the area overlying the ora serrata and posterior pars plana)' },{ id: 'd', text: 'Posterior lens capsule' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm7q7', module: 'Vitreous Body', text: 'Vitreous syneresis, the age-related liquefaction of the vitreous gel, is primarily caused by:', options: [{ id: 'a', text: 'Inflammation' },{ id: 'b', text: 'A breakdown in the collagen-hyaluronan network' },{ id: 'c', text: 'Neovascularization' },{ id: 'd', text: 'Hemorrhage' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm7q8', module: 'Vitreous Body', text: 'The Cloquet\'s canal is a transparent, S-shaped tube running through the vitreous body that represents a remnant of which embryonic structure?', options: [{ id: 'a', text: 'Hyaloid artery' },{ id: 'b', text: 'Retinal artery' },{ id: 'c', text: 'Choroidal vessels' },{ id: 'd', text: 'Pupillary membrane' }], correctAnswer: 'a', difficulty: 'easy', points: 1 },
    { id: 'm7q9', module: 'Vitreous Body', text: 'The vitreous humor makes up approximately what percentage of the eye\'s total volume?', options: [{ id: 'a', text: '20%' },{ id: 'b', text: '40%' },{ id: 'c', text: '60%' },{ id: 'd', text: '80%' }], correctAnswer: 'd', difficulty: 'easy', points: 1 },
    { id: 'm7q10', module: 'Vitreous Body', text: 'Which of the following is NOT a common cause of a vitreous hemorrhage?', options: [{ id: 'a', text: 'Proliferative diabetic retinopathy' },{ id: 'b', text: 'A retinal tear with vessel involvement' },{ id: 'c', text: 'Posterior vitreous detachment with a vessel avulsion' },{ id: 'd', text: 'Open-angle glaucoma' }], correctAnswer: 'd', difficulty: 'easy', points: 1 },

    // Module 8: Retina (Total Points: 24)
    { id: 'm8q1', module: 'Retina', text: 'Which photoreceptor cell is responsible for high-acuity color vision in bright light (photopic vision)?', options: [{ id: 'a', text: 'Rods' },{ id: 'b', text: 'Cones' },{ id: 'c', text: 'Ganglion cells' },{ id: 'd', text: 'Bipolar cells' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm8q2', module: 'Retina', text: 'The fovea centralis, the area of sharpest central vision, is characterized by a high density of which cells and an absence of which others?', options: [{ id: 'a', text: 'High density of rods, absence of cones' },{ id: 'b', text: 'High density of cones, absence of rods and overlying retinal layers' },{ id: 'c', text: 'Equal density of rods and cones' },{ id: 'd', text: 'High density of ganglion cells, absence of photoreceptors' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm8q3', module: 'Retina', text: 'A 75-year-old patient reports that straight lines, like a door frame, appear wavy or distorted (metamorphopsia). This symptom is highly specific for pathology in which retinal area?', options: [{ id: 'a', text: 'The peripheral retina' },{ id: 'b', text: 'The optic nerve head' },{ id: 'c', text: 'The macula' },{ id: 'd', text: 'The retinal vasculature' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm8q4', module: 'Retina', text: 'A fundus exam reveals a "cherry-red spot" at the macula, surrounded by a pale, ischemic retina. This is a classic, pathognomonic sign of:', options: [{ id: 'a', text: 'Central Retinal Vein Occlusion (CRVO)' },{ id: 'b', text: 'Central Retinal Artery Occlusion (CRAO)' },{ id: 'c', text: 'Proliferative Diabetic Retinopathy' },{ id: 'd', text: 'Rhegmatogenous Retinal Detachment' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm8q5', module: 'Retina', text: 'The neurosensory retina is composed of how many distinct layers that can be identified on histology or high-resolution OCT?', options: [{ id: 'a', text: '3' },{ id: 'b', text: '6' },{ id: 'c', text: '9 (plus the RPE as the 10th layer)' },{ id: 'd', text: '12' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm8q6', module: 'Retina', text: 'A crucial function of the Retinal Pigment Epithelium (RPE) is phagocytosis. What does the RPE primarily phagocytose as part of the visual cycle?', options: [{ id: 'a', text: 'Apoptotic ganglion cells' },{ id: 'b', text: 'Extracellular debris and drusen' },{ id: 'c', text: 'The shed outer segments of photoreceptors' },{ id: 'd', text: 'Extravasated red blood cells' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm8q7', module: 'Retina', text: 'The axons of which retinal cells bundle together to form the optic nerve?', options: [{ id: 'a', text: 'Photoreceptor cells' },{ id: 'b', text: 'Bipolar cells' },{ id: 'c', text: 'Ganglion cells' },{ id: 'd', text: 'Amacrine cells' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm8q8', module: 'Retina', text: 'A fundus exam of a diabetic patient reveals significant cotton-wool spots, venous beading, and intraretinal microvascular abnormalities (IRMA) in all four quadrants, but no neovascularization. According to the ETDRS classification, what is the correct diagnosis?', options: [{ id: 'a', text: 'Mild NPDR' },{ id: 'b', text: 'Moderate NPDR' },{ id: 'c', text: 'Severe NPDR (4-2-1 Rule)' },{ id: 'd', text: 'Proliferative Diabetic Retinopathy (PDR)' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm8q9', module: 'Retina', text: 'A patient complaining of a "curtain" or "shadow" descending over their peripheral vision, which has been present for a day, is a classic symptom of:', options: [{ id: 'a', text: 'A posterior vitreous detachment' },{ id: 'b', text: 'A rhegmatogenous retinal detachment' },{ id: 'c', text: 'A macular hole' },{ id: 'd', text: 'An epiretinal membrane' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm8q10', module: 'Retina', text: 'The photopigment found in rod cells, which is highly sensitive to light and crucial for scotopic vision, is called:', options: [{ id: 'a', text: 'Photopsin' },{ id: 'b', text: 'Melanopsin' },{ id: 'c', text: 'Rhodopsin' },{ id: 'd', text: 'All of the above' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },

    // Module 9: Optic Nerve & Pathways (Total Points: 24)
    { id: 'm9q1', module: 'Optic Nerve & Pathways', text: 'The optic disc represents the anatomical location of the:', options: [{ id: 'a', text: 'Fovea' },{ id: 'b', text: 'Macula' },{ id: 'c', text: 'Physiological blind spot' },{ id: 'd', text: 'Ora serrata' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm9q2', module: 'Optic Nerve & Pathways', text: 'A patient presents with a loss of vision in the outer half of both the left and right visual fields (bitemporal hemianopia). This specific visual field defect is pathognomonic for a lesion compressing the:', options: [{ id: 'a', text: 'Left Optic Nerve' },{ id: 'b', text: 'Optic Chiasm' },{ id: 'c', text: 'Right Optic Tract' },{ id: 'd', text: 'Visual Cortex' }], correctAnswer: 'b', difficulty: 'hard', points: 5 },
    { id: 'm9q3', module: 'Optic Nerve & Pathways', text: 'The vertical cup-to-disc ratio is a critical clinical measurement used to diagnose and monitor the progression of which optic neuropathy?', options: [{ id: 'a', text: 'Leber\'s Hereditary Optic Neuropathy' },{ id: 'b', text: 'Ischemic Optic Neuropathy' },{ id: 'c', text: 'Glaucoma' },{ id: 'd', text: 'Optic Neuritis' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm9q4', module: 'Optic Nerve & Pathways', text: 'At the optic chiasm, nerve fibers from the nasal half of each retina decussate. What happens to fibers from the temporal half of each retina?', options: [{ id: 'a', text: 'They also decussate to the opposite side' },{ id: 'b', text: 'They remain on the same side and travel down the ipsilateral optic tract' },{ id: 'c', text: 'They terminate at the chiasm' },{ id: 'd', 'text': 'They merge with the nasal fibers from the same eye' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm9q5', module: 'Optic Nerve & Pathways', text: 'A patient has a right homonymous hemianopia with macular sparing. This classic visual field defect is most commonly caused by an occlusion of which artery?', options: [{ id: 'a', text: 'Right Middle Cerebral Artery' },{ id: 'b', text: 'Left Middle Cerebral Artery' },{ id: 'c', text: 'Left Posterior Cerebral Artery' },{ id: 'd', text: 'Basilar Artery' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm9q6', module: 'Optic Nerve & Pathways', text: 'Papilledema is defined as bilateral optic disc swelling that is specifically caused by:', options: [{ id: 'a', text: 'High intraocular pressure (glaucoma)' },{ id: 'b', text: 'Inflammation of the optic nerve (optic neuritis)' },{ id: 'c', text: 'Ischemia (non-arteritic ischemic optic neuropathy)' },{ id: 'd', text: 'Increased intracranial pressure' }], correctAnswer: 'd', difficulty: 'medium', points: 2 },
    { id: 'm9q7', module: 'Optic Nerve & Pathways', text: 'Most of the axons in the optic tract, which carry visual information, synapse in which relay station within the thalamus?', options: [{ id: 'a', text: 'Medial Geniculate Nucleus' },{ id: 'b', text: 'Lateral Geniculate Nucleus (LGN)' },{ id: 'c', text: 'Pulvinar' },{ id: 'd', text: 'Superior Colliculus' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm9q8', module: 'Optic Nerve & Pathways', text: 'The characteristic pattern of early glaucomatous visual field loss most commonly follows the:', options: [{ id: 'a', text: 'Horizontal meridian (altitudinal defect)' },{ id: 'b', text: 'Vertical meridian (hemianopic defect)' },{ id: 'c', text: 'Arcuate pattern of the retinal nerve fiber layer, often presenting as a nasal step' },{ id: 'd', text: 'Central scotoma pattern' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm9q9', module: 'Optic Nerve & Pathways', text: 'Optic neuritis, characterized by acute, often painful, vision loss and a relative afferent pupillary defect, is most strongly associated with which systemic demyelinating disease?', options: [{ id: 'a', text: 'Diabetes Mellitus' },{ id: 'b', text: 'Multiple Sclerosis (MS)' },{ id: 'c', text: 'Systemic Lupus Erythematosus' },{ id: 'd', text: 'Rheumatoid Arthritis' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm9q10', module: 'Optic Nerve & Pathways', text: 'A key feature that distinguishes a post-chiasmal visual field defect from a pre-chiasmal (retinal or optic nerve) defect is that it:', options: [{ id: 'a', text: 'Is always absolute and dense' },{ id: 'b', text: 'Respects the vertical midline (is homonymous)' },{ id: 'c', text: 'Respects the horizontal midline (is altitudinal)' },{ id: 'd', text: 'Is always associated with a relative afferent pupillary defect' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },

    // Module 10: Extraocular Muscles & Ocular Motility (Total Points: 16)
    { id: 'm10q1', module: 'Extraocular Muscles & Ocular Motility', text: 'Which muscle is the primary abductor of the eye, moving it outward, away from the nose?', options: [{ id: 'a', text: 'Medial Rectus' },{ id: 'b', text: 'Lateral Rectus' },{ id: 'c', text: 'Superior Rectus' },{ id: 'd', text: 'Inferior Rectus' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm10q2', module: 'Extraocular Muscles & Ocular Motility', text: 'The superior oblique muscle, responsible for intorsion and depression, is uniquely innervated by which cranial nerve?', options: [{ id: 'a', text: 'CN III (Oculomotor)' },{ id: 'b', text: 'CN IV (Trochlear)' },{ id: 'c', text: 'CN V (Trigeminal)' },{ id: 'd', text: 'CN VI (Abducens)' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm10q3', module: 'Extraocular Muscles & Ocular Motility', text: 'A patient is asked to look to their right. According to Hering\'s Law of Equal Innervation, which two yoke muscles receive equal and simultaneous stimulation for this gaze?', options: [{ id: 'a', text: 'Right Lateral Rectus and Left Lateral Rectus' },{ id: 'b', text: 'Right Medial Rectus and Left Lateral Rectus' },{ id: 'c', text: 'Right Lateral Rectus and Left Medial Rectus' },{ id: 'd', text: 'Right Superior Rectus and Left Inferior Oblique' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm10q4', module: 'Extraocular Muscles & Ocular Motility', text: 'A patient presents with their left eye positioned "down and out," accompanied by significant ptosis and a dilated, non-reactive pupil. This triad of signs strongly suggests a complete palsy of which cranial nerve?', options: [{ id: 'a', text: 'Left CN III (Oculomotor)' },{ id: 'b', text: 'Left CN IV (Trochlear)' },{ id: 'c', text: 'Left CN VI (Abducens)' },{ id: 'd', text: 'Right CN III (Oculomotor)' }], correctAnswer: 'a', difficulty: 'medium', points: 2 },
    { id: 'm10q5', module: 'Extraocular Muscles & Ocular Motility', text: 'The primary action of the inferior oblique muscle is:', options: [{ id: 'a', text: 'Incyclotorsion' },{ id: 'b', text: 'Depression' },{ id: 'c', text: 'Abduction' },{ id: 'd', text: 'Excyclotorsion' }], correctAnswer: 'd', difficulty: 'medium', points: 2 },
    { id: 'm10q6', module: 'Extraocular Muscles & Ocular Motility', text: 'A patient reports sudden onset of vertical diplopia that worsens when they look down and to their left. They compensate by tilting their head to the right. This is a classic presentation of a palsy of which muscle/nerve?', options: [{ id: 'a', text: 'Left Superior Rectus' },{ id: 'b', 'text': 'Right Inferior Rectus' },{ id: 'c', text: 'Right Superior Oblique (CN IV)' },{ id: 'd', text: 'Left Inferior Oblique' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm10q7', module: 'Extraocular Muscles & Ocular Motility', text: 'Strabismus is the clinical term for any:', options: [{ id: 'a', text: 'Reduction in vision (amblyopia)' },{ id: 'b', text: 'Double vision (diplopia)' },{ id: 'c', text: 'Misalignment of the visual axes of the eyes' },{ id: 'd', text: 'Involuntary, rhythmic oscillation of the eyes (nystagmus)' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm10q8', module: 'Extraocular Muscles & Ocular Motility', text: 'Which extraocular muscle is unique in that it originates from the anterior orbital floor, not from the common tendinous ring (annulus of Zinn) at the orbital apex?', options: [{ id: 'a', text: 'Superior Rectus' },{ id: 'b', text: 'Medial Rectus' },{ id: 'c', text: 'Lateral Rectus' },{ id: 'd', text: 'Inferior Oblique' }], correctAnswer: 'd', difficulty: 'easy', points: 1 },
    { id: 'm10q9', module: 'Extraocular Muscles & Ocular Motility', text: 'The "H-pattern" motility test is a fundamental clinical examination used to:', options: [{ id: 'a', text: 'Assess pupillary light reflexes' },{ id: 'b', text: 'Measure intraocular pressure in different gazes' },{ id: 'c', text: 'Isolate and test the primary action of each of the six extraocular muscles in their respective diagnostic fields of gaze' },{ id: 'd', text: 'Evaluate the peripheral visual field' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm10q10', module: 'Extraocular Muscles & Ocular Motility', text: 'Sherrington\'s Law of Reciprocal Innervation explains that when an agonist muscle (e.g., the medial rectus) contracts for a specific eye movement, what happens to its direct antagonist in the same eye?', options: [{ id: 'a', text: 'Its contralateral yoke muscle also contracts' },{ id: 'b', text: 'Its ipsilateral antagonist muscle (e.g., the lateral rectus) relaxes' },{ id: 'c', text: 'Its ipsilateral antagonist muscle also contracts (co-contraction)' },{ id: 'd', text: 'All other extraocular muscles relax' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },

];
