
export type Question = {
    id: string;
    module: string;
    text: string;
    options: { id: 'a' | 'b' | 'c' | 'd'; text: string }[];
    correctAnswer: 'a' | 'b' | 'c' | 'd';
    difficulty: 'easy' | 'medium' | 'hard';
    points: 1 | 2 | 5;
};

export const quizModules = [
  { topic: 'Eyelids & Adnexa', time: 5 * 60 },
  { topic: 'Conjunctiva & Sclera', time: 6 * 60 },
  { topic: 'Cornea', time: 7 * 60 },
  { topic: 'Anterior Chamber & Aqueous Humor', time: 6 * 60 },
  { topic: 'Iris & Pupil', time: 6 * 60 },
  { topic: 'Crystalline Lens & Accommodation', time: 7 * 60 },
  { topic: 'Vitreous Body', time: 5 * 60 },
  { topic: 'Retina', time: 9 * 60 },
  { topic: 'Optic Nerve & Pathways', time: 9 * 60 },
  { topic: 'Extraocular Muscles & Ocular Motility', time: 5 * 60 },
];

export const questions: Question[] = [
    // Module 1: Eyelids & Adnexa (Total Points: 18)
    {
        id: 'm1q1',
        module: 'Eyelids & Adnexa',
        text: 'Which gland is responsible for the oily layer of the tear film?',
        options: [
            { id: 'a', text: 'Lacrimal Gland' },
            { id: 'b', text: 'Glands of Krause' },
            { id: 'c', text: 'Meibomian Gland' },
            { id: 'd', text: 'Glands of Wolfring' },
        ],
        correctAnswer: 'c',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm1q2',
        module: 'Eyelids & Adnexa',
        text: "Bell's phenomenon is the upward and outward rotation of the eyeball on attempted closure of the eyelids. Which cranial nerve mediates this reflex?",
        options: [
            { id: 'a', text: 'CN III (Oculomotor)' },
            { id: 'b', text: 'CN V (Trigeminal)' },
            { id: 'c', text: 'CN IV (Trochlear)' },
            { id: 'd', text: 'CN VII (Facial)' },
        ],
        correctAnswer: 'd',
        difficulty: 'medium',
        points: 2,
    },
     {
        id: 'm1q3',
        module: 'Eyelids & Adnexa',
        text: 'Ptosis refers to the drooping of which structure?',
        options: [
            { id: 'a', text: 'Lower eyelid' },
            { id: 'b', text: 'Upper eyelid' },
            { id: 'c', text: 'Eyebrow' },
            { id: 'd', text: 'Conjunctiva' },
        ],
        correctAnswer: 'b',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm1q4',
        module: 'Eyelids & Adnexa',
        text: 'A 60-year-old patient presents with an inwardly turned lower eyelid, causing irritation from their eyelashes. What is the most likely diagnosis?',
        options: [
            { id: 'a', text: 'Ectropion' },
            { id: 'b', text: 'Chalazion' },
            { id: 'c', text: 'Entropion' },
            { id: 'd', text: 'Blepharitis' },
        ],
        correctAnswer: 'c',
        difficulty: 'hard',
        points: 5,
    },
     {
        id: 'm1q5',
        module: 'Eyelids & Adnexa',
        text: 'A chalazion is a painless, granulomatous inflammation resulting from a blockage of which gland?',
        options: [
            { id: 'a', text: 'Gland of Zeis' },
            { id: 'b', text: 'Gland of Moll' },
            { id: 'c', text: 'Meibomian Gland' },
            { id: 'd', text: 'Lacrimal Gland' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm1q6',
        module: 'Eyelids & Adnexa',
        text: 'The palpebral conjunctiva lines which surface?',
        options: [
            { id: 'a', text: 'The anterior surface of the sclera' },
            { id: 'b', text: 'The posterior surface of the eyelids' },
            { id: 'c', text: 'The cornea' },
            { id: 'd', text: 'The fornix' },
        ],
        correctAnswer: 'b',
        difficulty: 'easy',
        points: 1,
    },
     {
        id: 'm1q7',
        module: 'Eyelids & Adnexa',
        text: 'Which part of the lacrimal drainage system is the first point of tear entry?',
        options: [
            { id: 'a', text: 'Lacrimal sac' },
            { id: 'b', text: 'Nasolacrimal duct' },
            { id: 'c', text: 'Canaliculi' },
            { id: 'd', text: 'Lacrimal puncta' },
        ],
        correctAnswer: 'd',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm1q8',
        module: 'Eyelids & Adnexa',
        text: 'An external hordeolum (stye) is an acute infection of which gland at the base of the eyelashes?',
        options: [
            { id: 'a', text: 'Meibomian gland' },
            { id: 'b', text: 'Gland of Zeis or Moll' },
            { id: 'c', text: 'Accessory lacrimal gland' },
            { id: 'd', text: 'Goblet cell' },
        ],
        correctAnswer: 'b',
        difficulty: 'medium',
        points: 2,
    },
     {
        id: 'm1q9',
        module: 'Eyelids & Adnexa',
        text: 'The "gray line" of the eyelid margin, an important surgical landmark, represents the location of the:',
        options: [
            { id: 'a', text: 'Meibomian gland orifices' },
            { id: 'b', text: 'Insertion of the levator aponeurosis' },
            { id: 'c', text: 'Muscle of Riolan (a portion of the orbicularis oculi)' },
            { id: 'd', text: 'Tarsal plate border' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm1q10',
        module: 'Eyelids & Adnexa',
        text: 'Which muscle is primarily responsible for eyelid closure (blinking)?',
        options: [
            { id: 'a', text: 'Levator palpebrae superioris' },
            { id: 'b', text: 'Müller\'s muscle' },
            { id: 'c', text: 'Frontalis muscle' },
            { id: 'd', text: 'Orbicularis oculi' },
        ],
        correctAnswer: 'd',
        difficulty: 'easy',
        points: 1,
    },

    // Module 2: Conjunctiva & Sclera (Total Points: 17)
    {
        id: 'm2q1',
        module: 'Conjunctiva & Sclera',
        text: 'Which cells in the conjunctiva are responsible for producing mucin, a key component of the tear film?',
        options: [
            { id: 'a', text: 'Epithelial cells' },
            { id: 'b', text: 'Goblet cells' },
            { id: 'c', text: 'Melanocytes' },
            { id: 'd', text: 'Langerhans cells' },
        ],
        correctAnswer: 'b',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm2q2',
        module: 'Conjunctiva & Sclera',
        text: 'A pinguecula is a degenerative condition of the conjunctiva, presenting as a yellowish, slightly raised deposit. Where is it most commonly found?',
        options: [
            { id: 'a', text: 'Superior bulbar conjunctiva' },
            { id: 'b', text: 'Inferior palpebral conjunctiva' },
            { id: 'c', text: 'Nasal and temporal interpalpebral conjunctiva' },
            { id: 'd', text: 'Forniceal conjunctiva' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
     {
        id: 'm2q3',
        module: 'Conjunctiva & Sclera',
        text: 'The sclera is thinnest at which point?',
        options: [
            { id: 'a', text: 'At the limbus' },
            { id: 'b', text: 'At the posterior pole' },
            { id: 'c', text: 'Just behind the insertions of the extraocular rectus muscles' },
            { id: 'd', text: 'At the equator' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm2q4',
        module: 'Conjunctiva & Sclera',
        text: 'A 30-year-old patient presents with sectoral redness and mild discomfort. Phenylephrine 2.5% drops are instilled, and the redness blanches significantly. This finding is most consistent with:',
        options: [
            { id: 'a', text: 'Scleritis' },
            { id: 'b', text: 'Episcleritis' },
            { id: 'c', text: 'Conjunctivitis' },
            { id: 'd', text: 'Uveitis' },
        ],
        correctAnswer: 'b',
        difficulty: 'hard',
        points: 5,
    },
     {
        id: 'm2q5',
        module: 'Conjunctiva & Sclera',
        text: 'The palisades of Vogt, a crucial source of corneal epithelial stem cells, are located in which region?',
        options: [
            { id: 'a', text: 'The bulbar conjunctiva' },
            { id: 'b', text: 'The tarsal conjunctiva' },
            { id: 'c', text: 'The limbus' },
            { id: 'd', text: 'The fornix' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm2q6',
        module: 'Conjunctiva & Sclera',
        text: 'Giant papillary conjunctivitis (GPC) is most commonly associated with:',
        options: [
            { id: 'a', text: 'Viral infections' },
            { id: 'b', text: 'Bacterial infections' },
            { id: 'c', text: 'Contact lens wear' },
            { id: 'd', text: 'Seasonal allergies' },
        ],
        correctAnswer: 'c',
        difficulty: 'easy',
        points: 1,
    },
     {
        id: 'm2q7',
        module: 'Conjunctiva & Sclera',
        text: 'What is the primary structural protein that gives the sclera its strength and white color?',
        options: [
            { id: 'a', text: 'Elastin' },
            { id: 'b', text: 'Keratin' },
            { id: 'c', text: 'Collagen Type I' },
            { id: 'd', text: 'Fibronectin' },
        ],
        correctAnswer: 'c',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm2q8',
        module: 'Conjunctiva & Sclera',
        text: 'The lamina fusca is the innermost layer of the sclera, characterized by a high concentration of:',
        options: [
            { id: 'a', text: 'Fibroblasts' },
            { id: 'b', text: 'Melanocytes' },
            { id: 'c', text: 'Goblet cells' },
            { id: 'd', text: 'Collagen fibers' },
        ],
        correctAnswer: 'b',
        difficulty: 'medium',
        points: 2,
    },
     {
        id: 'm2q9',
        module: 'Conjunctiva & Sclera',
        text: 'Which type of conjunctival injection is characterized by deep, non-moving vessels and is often associated with more severe ocular conditions like uveitis or scleritis?',
        options: [
            { id: 'a', text: 'Papillary injection' },
            { id: 'b', text: 'Follicular injection' },
            { id: 'c', text: 'Ciliary flush (circumcorneal injection)' },
            { id: 'd', text: 'Diffuse injection' },
        ],
        correctAnswer: 'c',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm2q10',
        module: 'Conjunctiva & Sclera',
        text: 'A pterygium is a triangular growth of fibrovascular tissue that typically originates from the:',
        options: [
            { id: 'a', text: 'Palpebral conjunctiva and grows onto the eyelid margin' },
            { id: 'b', text: 'Bulbar conjunctiva and grows onto the cornea' },
            { id: 'c', text: 'Sclera and grows over the iris' },
            { id: 'd', text: 'Fornix and grows towards the limbus' },
        ],
        correctAnswer: 'b',
        difficulty: 'easy',
        points: 1,
    },

    // Module 3: Cornea (Total Points: 20)
    {
        id: 'm3q1',
        module: 'Cornea',
        text: 'Which layer of the cornea is primarily responsible for maintaining its dehydrated state (deturgescence) via an active pump mechanism?',
        options: [
            { id: 'a', text: 'Epithelium' },
            { id: 'b', text: 'Bowman\'s Layer' },
            { id: 'c', text: 'Stroma' },
            { id: 'd', text: 'Endothelium' },
        ],
        correctAnswer: 'd',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm3q2',
        module: 'Cornea',
        text: 'The majority of the cornea\'s total refractive power comes from:',
        options: [
            { id: 'a', text: 'The posterior corneal surface' },
            { id: 'b', text: 'The anterior corneal surface (air-tear film interface)' },
            { id: 'c', text: 'The corneal stroma' },
            { id: 'd', text: 'The endothelium' },
        ],
        correctAnswer: 'b',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm3q3',
        module: 'Cornea',
        text: 'A 65-year-old patient reports hazy vision that is worst upon waking and improves throughout the day. Slit lamp exam reveals guttae and corneal edema. What is the most likely diagnosis?',
        options: [
            { id: 'a', text: 'Keratoconus' },
            { id: 'b', text: 'Fuchs\' Endothelial Dystrophy' },
            { id: 'c', text: 'Herpetic Keratitis' },
            { id: 'd', text: 'Corneal Abrasion' },
        ],
        correctAnswer: 'b',
        difficulty: 'hard',
        points: 5,
    },
    {
        id: 'm3q4',
        module: 'Cornea',
        text: 'A dendritic ulcer, visualized with fluorescein stain, is a classic pathognomonic sign of which type of keratitis?',
        options: [
            { id: 'a', text: 'Bacterial Keratitis' },
            { id: 'b', text: 'Fungal Keratitis' },
            { id: 'c', text: 'Herpes Simplex Keratitis' },
            { id: 'd', text: 'Acanthamoeba Keratitis' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm3q5',
        module: 'Cornea',
        text: 'What is the approximate average dioptric power of the human cornea?',
        options: [
            { id: 'a', text: '~20 D' },
            { id: 'b', text: '~33 D' },
            { id: 'c', text: '~43 D' },
            { id: 'd', text: '~58 D' },
        ],
        correctAnswer: 'c',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm3q6',
        module: 'Cornea',
        text: 'Which corneal layer is acellular, does not regenerate if damaged, and forms a scar instead?',
        options: [
            { id: 'a', text: 'Epithelium' },
            { id: 'b', text: 'Bowman\'s Layer' },
            { id: 'c', text: 'Stroma' },
            { id: 'd', text: 'Descemet\'s Membrane' },
        ],
        correctAnswer: 'b',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm3q7',
        module: 'Cornea',
        text: 'Under normal, eyes-open conditions, the cornea receives most of its oxygen supply from:',
        options: [
            { id: 'a', text: 'The limbal vasculature' },
            { id: 'b', text: 'The aqueous humor' },
            { id: 'c', text: 'The palpebral conjunctiva' },
            { id: 'd', text: 'The atmosphere' },
        ],
        correctAnswer: 'd',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm3q8',
        module: 'Cornea',
        text: 'A "Whorl Keratopathy" (vortex keratopathy), characterized by fine, golden-brown deposits in the corneal epithelium, is a well-known side effect of which systemic medication?',
        options: [
            { id: 'a', text: 'Ibuprofen' },
            { id: 'b', text: 'Amiodarone' },
            { id: 'c', text: 'Lisinopril' },
            { id: 'd', text: 'Metformin' },
        ],
        correctAnswer: 'b',
        difficulty: 'medium',
        points: 2,
    },
    {
        id: 'm3q9',
        module: 'Cornea',
        text: 'What happens to corneal endothelial cell density throughout a person\'s life?',
        options: [
            { id: 'a', text: 'It increases' },
            { id: 'b', text: 'It steadily decreases' },
            { id: 'c', text: 'It stays the same' },
            { id: 'd', text: 'It fluctuates seasonally' },
        ],
        correctAnswer: 'b',
        difficulty: 'easy',
        points: 1,
    },
    {
        id: 'm3q10',
        module: 'Cornea',
        text: 'The transparency of the cornea is primarily maintained by the highly regular, uniform arrangement of collagen fibrils in which layer?',
        options: [
            { id: 'a', text: 'Epithelium' },
            { id: 'b', text: 'Bowman\'s Layer' },
            { id: 'c', text: 'Stroma' },
            { id: 'd', text: 'Endothelium' },
        ],
        correctAnswer: 'c',
        difficulty: 'medium',
        points: 2,
    },
    
    // Module 4: Anterior Chamber & Aqueous Humor (Total Points: 16)
    { id: 'm4q1', module: 'Anterior Chamber & Aqueous Humor', text: 'Aqueous humor is actively secreted by which structure?', options: [{ id: 'a', text: 'Trabecular meshwork' }, { id: 'b', text: 'Non-pigmented epithelium of the ciliary body' }, { id: 'c', text: 'Schlemm\'s canal' }, { id: 'd', text: 'Iris stroma' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm4q2', module: 'Anterior Chamber & Aqueous Humor', text: 'What is the conventional (primary) pathway for aqueous humor outflow?', options: [{ id: 'a', text: 'Uveoscleral pathway' }, { id: 'b', text: 'Suprachoroidal space' }, { id: 'c', text: 'Through the iris root' }, { id: 'd', text: 'Trabecular meshwork -> Schlemm\'s canal -> episcleral veins' }], correctAnswer: 'd', difficulty: 'easy', points: 1 },
    { id: 'm4q3', module: 'Anterior Chamber & Aqueous Humor', text: 'Hyphema is the presence of what in the anterior chamber?', options: [{ id: 'a', text: 'Pus (white blood cells)' },{ id: 'b', text: 'Red blood cells' },{ id: 'c', text: 'Lens particles' },{ id: 'd', text: 'Pigment cells' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm4q4', module: 'Anterior Chamber & Aqueous Humor', text: 'A patient with open-angle glaucoma is prescribed latanoprost. What is the primary mechanism of action for this medication?', options: [{ id: 'a', text: 'Decreasing aqueous production' },{ id: 'b', text: 'Increasing trabecular outflow' },{ id: 'c', text: 'Increasing uveoscleral outflow' },{ id: 'd', text: 'Constricting the pupil' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm4q5', module: 'Anterior Chamber & Aqueous Humor', text: 'The normal depth of the central anterior chamber in an adult is typically around:', options: [{ id: 'a', text: '1.5 mm' },{ id: 'b', text: '2.0 mm' },{ id: 'c', text: '3.5 mm' },{ id: 'd', text: '5.0 mm' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm4q6', module: 'Anterior Chamber & Aqueous Humor', text: 'Compared to blood plasma, aqueous humor has a significantly lower concentration of _____ and a higher concentration of _____.', options: [{ id: 'a', text: 'Ascorbate, Protein' },{ id: 'b', text: 'Protein, Ascorbate' },{ id: 'c', text: 'Glucose, Lactate' },{ id: 'd', text: 'Sodium, Potassium' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm4g7', module: 'Anterior Chamber & Aqueous Humor', text: 'The angle of the anterior chamber is the anatomical junction between the:', options: [{ id: 'a', text: 'Iris and Lens' },{ id: 'b', text: 'Cornea and Ciliary body' },{ id: 'c', text: 'Peripheral cornea and the root of the iris' },{ id: 'd', text: 'Lens and Sclera' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm4q8', module: 'Anterior Chamber & Aqueous Humor', text: 'Gonioscopy is a clinical technique used to visualize the:', options: [{ id: 'a', text: 'Retinal periphery' },{ id: 'b', text: 'Optic nerve head' },{ id: 'c', text: 'Vitreous body' },{ id: 'd', text: 'Anterior chamber angle' }], correctAnswer: 'd', difficulty: 'easy', points: 1 },
    { id: 'm4q9', module: 'Anterior Chamber & Aqueous Humor', text: 'A Krukenberg spindle, a vertical line of pigment on the corneal endothelium, is a classic sign of what condition?', options: [{ id: 'a', text: 'Uveitis' },{ id: 'b', text: 'Pigment dispersion syndrome' },{ id: 'c', text: 'Pseudoexfoliation syndrome' },{ id: 'd', text: 'Fuchs\' dystrophy' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm4q10', module: 'Anterior Chamber & Aqueous Humor', text: 'Which medication class reduces aqueous production by inhibiting the enzyme responsible for bicarbonate formation in the ciliary epithelium?', options: [{ id: 'a', text: 'Beta-blockers (e.g., Timolol)' },{ id: 'b', text: 'Prostaglandin analogs (e.g., Latanoprost)' },{ id: 'c', text: 'Carbonic anhydrase inhibitors (e.g., Dorzolamide)' },{ id: 'd', text: 'Alpha-agonists (e.g., Brimonidine)' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },


    // Module 5: Iris & Pupil (Total Points: 15)
    { id: 'm5q1', module: 'Iris & Pupil', text: 'The color of the iris is primarily determined by the amount and type of melanin in which layer(s)?', options: [{ id: 'a', text: 'Anterior border layer & Stroma' },{ id: 'b', text: 'Posterior pigment epithelium' },{ id: 'c', text: 'Dilator muscle' },{ id: 'd', text: 'Sphincter muscle' }], correctAnswer: 'a', difficulty: 'medium', points: 2 },
    { id: 'm5q2', module: 'Iris & Pupil', text: 'Pupillary constriction (miosis) is controlled by which muscle and which branch of the autonomic nervous system?', options: [{ id: 'a', text: 'Dilator pupillae, Sympathetic' },{ id: 'b', text: 'Sphincter pupillae, Sympathetic' },{ id: 'c', text: 'Sphincter pupillae, Parasympathetic' },{ id: 'd', text: 'Dilator pupillae, Parasympathetic' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm5q3', module: 'Iris & Pupil', text: 'Anisocoria refers to:', options: [{ id: 'a', text: 'An irregularly shaped pupil' },{ id: 'b', text: 'A difference in pupil size between the two eyes' },{ id: 'c', text: 'A poor reaction to light' },{ id: 'd', text: 'Inflammation of the iris' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm5q4', module: 'Iris & Pupil', text: 'A patient exhibits a left relative afferent pupillary defect (RAPD). When a light is swung from the right eye to the left eye, what will the left pupil do?', options: [{ id: 'a', text: 'Constrict strongly' },{ id: 'b', text: 'Remain unchanged' },{ id: 'c', text: 'Dilate' },{ id: 'd', text: 'Constrict and then immediately dilate' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm5q5', module: 'Iris & Pupil', text: 'Pharmacologic dilation of the pupil is called:', options: [{ id: 'a', text: 'Miosis' },{ id: 'b', text: 'Mydriasis' },{ id: 'c', text: 'Cycloplegia' },{ id: 'd', text: 'Anisocoria' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm5q6', module: 'Iris & Pupil', text: 'The efferent pathway for the pupillary light reflex travels along which cranial nerve?', options: [{ id: 'a', text: 'Optic nerve (CN II)' },{ id: 'b', text: 'Oculomotor nerve (CN III)' },{ id: 'c', text: 'Trigeminal nerve (CN V)' },{ id: 'd', text: 'Abducens nerve (CN VI)' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm5q7', module: 'Iris & Pupil', text: 'The iris collarette is an anatomical landmark that separates the:', options: [{ id: 'a', text: 'Anterior and posterior iris surfaces' },{ id: 'b', text: 'Pupillary zone and ciliary zone' },{ id: 'c', text: 'Iris stroma and posterior epithelium' },{ id: 'd', text: 'Sphincter and dilator muscles' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm5q8', module: 'Iris & Pupil', text: 'Which condition is characterized by inflammation of the iris and ciliary body?', options: [{ id: 'a', text: 'Iritis' },{ id: 'b', text: 'Iridocyclitis' },{ id: 'c', text: 'Keratitis' },{ id: 'd', text: 'Scleritis' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm5q9', module: 'Iris & Pupil', text: 'In Horner\'s Syndrome, the classic triad of signs is ptosis, anhydrosis, and:', options: [{ id: 'a', text: 'Mydriasis (dilation)' },{ id: 'b', text: 'Miosis (constriction)' },{ id: 'c', text: 'A fixed, non-reactive pupil' },{ id: 'd', text: 'An irregularly shaped pupil' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm5q10', module: 'Iris & Pupil', text: 'The near reflex triad consists of:', options: [{ id: 'a', text: 'Pupil constriction, accommodation, and divergence' },{ id: 'b', text: 'Pupil dilation, accommodation, and convergence' },{ id: 'c', text: 'Pupil constriction, accommodation, and convergence' },{ id: 'd', text: 'Pupil constriction, lens thinning, and divergence' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },

    // Module 6: Crystalline Lens & Accommodation (Total Points: 19)
    { id: 'm6q1', module: 'Crystalline Lens & Accommodation', text: 'What is the primary dynamic function of the crystalline lens?', options: [{ id: 'a', text: 'To absorb UV light' },{ id: 'b', text: 'To produce aqueous humor' },{ id: 'c', text: 'To provide the majority of the eye\'s refractive power' },{ id: 'd', text: 'To change shape to focus on objects at different distances' }], correctAnswer: 'd', difficulty: 'easy', points: 1 },
    { id: 'm6q2', module: 'Crystalline Lens & Accommodation', text: 'A cataract is an opacification of which structure?', options: [{ id: 'a', text: 'Cornea' },{ id: 'b', 'text': 'Vitreous' },{ id: 'c', text: 'Crystalline lens' },{ id: 'd', text: 'Retina' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm6q3', module: 'Crystalline Lens & Accommodation', text: 'During accommodation, what happens to the ciliary muscle, zonular fibers, and the lens?', options: [{ id: 'a', text: 'Muscle relaxes, zonules tighten, lens flattens' },{ id: 'b', text: 'Muscle contracts, zonules relax, lens becomes more convex' },{ id: 'c', text: 'Muscle contracts, zonules tighten, lens becomes more convex' },{ id: 'd', text: 'Muscle relaxes, zonules relax, lens flattens' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm6q4', module: 'Crystalline Lens & Accommodation', text: 'A patient with uncontrolled diabetes develops a "snowflake" cataract. This rapid-onset cataract is due to osmotic over-hydration of the lens caused by the accumulation of:', options: [{ id: 'a', text: 'Lactic acid' },{ id: 'b', text: 'Sorbitol' },{ id: 'c', text: 'Cholesterol' },{ id: 'd', text: 'Advanced glycation end-products' }], correctAnswer: 'b', difficulty: 'hard', points: 5 },
    { id: 'm6q5', module: 'Crystalline Lens & Accommodation', text: 'A posterior subcapsular cataract is most commonly associated with which risk factor and typically causes what primary symptom?', options: [{ id: 'a', text: 'Aging; blurry distance vision' },{ id: 'b', text: 'Long-term steroid use; glare and difficulty reading' },{ id: 'c', text: 'Diabetes; myopic shift' },{ id: 'd', text: 'Myopia; halos around lights' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm6q6', module: 'Crystalline Lens & Accommodation', text: 'The lens capsule is an elastic basement membrane primarily composed of what type of protein?', options: [{ id: 'a', text: 'Crystallins' },{ id: 'b', text: 'Elastin' },{ id: 'c', text: 'Type IV collagen' },{ id: 'd', text: 'Actin' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm6q7', module: 'Crystalline Lens & Accommodation', text: 'What is the term for the condition where the crystalline lens is displaced from its normal position, often seen in Marfan syndrome?', options: [{ id: 'a', text: 'Aphakia' },{ id: 'b', text: 'Pseudophakia' },{ id: 'c', text: 'Ectopia lentis' },{ id: 'd', text: 'Phacoemulsification' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm6q8', module: 'Crystalline Lens & Accommodation', text: 'Which type of cataract often causes a "myopic shift," where a patient becomes more near-sighted?', options: [{ id: 'a', text: 'Nuclear sclerotic' },{ id: 'b', text: 'Cortical' },{ id: 'c', text: 'Posterior subcapsular' },{ id: 'd', text: 'Traumatic' }], correctAnswer: 'a', difficulty: 'medium', points: 2 },
    { id: 'm6q9', module: 'Crystalline Lens & Accommodation', text: 'The amplitude of accommodation is measured in:', options: [{ id: 'a', text: 'Millimeters (mm)' },{ id: 'b', text: 'Prism diopters (PD)' },{ id: 'c', text: 'Diopters (D)' },{ id: 'd', text: 'Degrees (°)' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm6q10', module: 'Crystalline Lens & Accommodation', text: 'What are the soluble proteins that make up the bulk of the lens fibers and are crucial for its transparency?', options: [{ id: 'a', text: 'Albumins' },{ id: 'b', text: 'Globulins' },{ id: 'c', text: 'Crystallins' },{ id: 'd', text: 'Collagens' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },

    // Module 7: Vitreous Body (Total Points: 15)
    { id: 'm7q1', module: 'Vitreous Body', text: 'The vitreous body is an inert, transparent gel primarily composed of:', options: [{ id: 'a', text: '99% water and collagen' },{ id: 'b', text: '99% water and hyaluronic acid' },{ id: 'c', text: '99% water, with a network of collagen and hyaluronic acid' },{ id: 'd', text: 'Hyaluronic acid and elastin' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm7q2', module: 'Vitreous Body', text: 'A posterior vitreous detachment (PVD) occurs when the vitreous cortex separates from the:', options: [{ id: 'a', text: 'Posterior lens capsule' },{ id: 'b', text: 'Ciliary body' },{ id: 'c', text: 'Internal limiting membrane of the retina' },{ id: 'd', text: 'Choroid' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm7q3', module: 'Vitreous Body', text: 'A 60-year-old patient suddenly experiences a "shower of black dots" and a "cobweb" in their vision. What is the most likely cause?', options: [{ id: 'a', text: 'Cataract progression' },{ id: 'b', text: 'Macular degeneration' },{ id: 'c', text: 'Acute posterior vitreous detachment (PVD)' },{ id: 'd', text: 'Migraine aura' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm7q4', module: 'Vitreous Body', text: 'What is the name of the ring-shaped floater that represents the detachment of the vitreous from around the optic nerve head?', options: [{ id: 'a', text: 'Muscae volitantes' },{ id: 'b', text: 'Vitreous syneresis' },{ id: 'c', text: 'Weiss ring' },{ id: 'd', text: 'Shafer\'s sign' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm7q5', module: 'Vitreous Body', text: 'Asteroid hyalosis consists of what type of spherical, yellowish-white deposits in the vitreous?', options: [{ id: 'a', text: 'Cholesterol crystals' },{ id: 'b', text: 'Calcium-phosphate soaps' },{ id: 'c', text: 'Red blood cells' },{ id: 'd', text: 'Pigment cells' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm7q6', module: 'Vitreous Body', text: 'The strongest attachment of the vitreous to the surrounding structures is at the:', options: [{ id: 'a', text: 'Optic disc margin' },{ id: 'b', text: 'Macula' },{ id: 'c', text: 'Vitreous base (near the ora serrata)' },{ id: 'd', text: 'Posterior lens capsule' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm7q7', module: 'Vitreous Body', text: 'Vitreous syneresis refers to:', options: [{ id: 'a', text: 'Inflammation of the vitreous' },{ id: 'b', text: 'Hemorrhage into the vitreous' },{ id: 'c', text: 'The age-related process of liquefaction and collapse of the vitreous gel' },{ id: 'd', text: 'The formation of new blood vessels in the vitreous' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm7q8', module: 'Vitreous Body', text: 'The Cloquet\'s canal is a transparent, S-shaped tube running through the vitreous, representing a remnant of the embryonic:', options: [{ id: 'a', text: 'Hyaloid artery' },{ id: 'b', text: 'Retinal artery' },{ id: 'c', text: 'Choroidal vessels' },{ id: 'd', text: 'Tarsal artery' }], correctAnswer: 'a', difficulty: 'easy', points: 1 },
    { id: 'm7q9', module: 'Vitreous Body', text: 'The volume of the vitreous humor accounts for approximately what percentage of the eye\'s total volume?', options: [{ id: 'a', text: '20%' },{ id: 'b', text: '40%' },{ id: 'c', text: '60%' },{ id: 'd', text: '80%' }], correctAnswer: 'd', difficulty: 'easy', points: 1 },
    { id: 'm7q10', module: 'Vitreous Body', text: 'A vitreous hemorrhage appears as diffuse haze or blood-filled areas and can be caused by all of the following EXCEPT:', options: [{ id: 'a', text: 'Proliferative diabetic retinopathy' },{ id: 'b', text: 'Retinal tear' },{ id: 'c', text: 'Posterior vitreous detachment' },{ id: 'd', text: 'Uncomplicated cataract surgery' }], correctAnswer: 'd', difficulty: 'easy', points: 1 },

    // Module 8: Retina (Total Points: 25)
    { id: 'm8q1', module: 'Retina', text: 'Which photoreceptor is responsible for scotopic (low-light) vision?', options: [{ id: 'a', text: 'Rods' },{ id: 'b', text: 'Cones' },{ id: 'c', text: 'Ganglion cells' },{ id: 'd', text: 'Bipolar cells' }], correctAnswer: 'a', difficulty: 'easy', points: 1 },
    { id: 'm8q2', module: 'Retina', text: 'The fovea centralis, the area of sharpest vision, contains a high density of which cells?', options: [{ id: 'a', text: 'Rods only' },{ id: 'b', text: 'Cones only' },{ id: 'c', text: 'Both rods and cones' },{ id: 'd', 'text': 'Ganglion cells only' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm8q3', module: 'Retina', text: 'A 75-year-old patient complains of straight lines appearing wavy (metamorphopsia). This symptom is most characteristic of:', options: [{ id: 'a', text: 'Cataracts' },{ id: 'b', text: 'Glaucoma' },{ id: 'c', text: 'Macular disease, such as AMD' },{ id: 'd', text: 'Dry eye syndrome' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm8q4', module: 'Retina', text: 'A "cherry-red spot" at the macula, surrounded by a pale retina, is a classic funduscopic sign of:', options: [{ id: 'a', text: 'Central Retinal Vein Occlusion (CRVO)' },{ id: 'b', text: 'Central Retinal Artery Occlusion (CRAO)' },{ id: 'c', text: 'Diabetic Retinopathy' },{ id: 'd', text: 'Retinal Detachment' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm8q5', module: 'Retina', text: 'How many distinct layers make up the neurosensory retina (excluding the RPE)?', options: [{ id: 'a', text: '3' },{ id: 'b', text: '6' },{ id: 'c', text: '9' },{ id: 'd', text: '10' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm8q6', module: 'Retina', text: 'A key function of the Retinal Pigment Epithelium (RPE) is phagocytosis. What does it phagocytose?', options: [{ id: 'a', text: 'Dead ganglion cells' },{ id: 'b', text: 'Extracellular debris' },{ id: 'c', text: 'Shed outer segments of photoreceptors' },{ id: 'd', text: 'Red blood cells' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm8q7', module: 'Retina', text: 'Which retinal cells have axons that form the optic nerve?', options: [{ id: 'a', text: 'Photoreceptor cells' },{ id: 'b', text: 'Bipolar cells' },{ id: 'c', text: 'Ganglion cells' },{ id: 'd', text: 'Amacrine cells' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm8q8', module: 'Retina', text: 'A fundus exam of a diabetic patient reveals neovascularization of the disc (NVD). This finding classifies the patient as having which stage of diabetic retinopathy?', options: [{ id: 'a', text: 'Mild NPDR' },{ id: 'b', text: 'Moderate NPDR' },{ id: 'c', text: 'Severe NPDR' },{ id: 'd', text: 'Proliferative Diabetic Retinopathy (PDR)' }], correctAnswer: 'd', difficulty: 'hard', points: 5 },
    { id: 'm8q9', module: 'Retina', text: 'A patient complaining of a "curtain" or "shadow" descending over their peripheral vision is a classic symptom of:', options: [{ id: 'a', text: 'A posterior vitreous detachment' },{ id: 'b', text: 'A retinal detachment' },{ id: 'c', text: 'A macular hole' },{ id: 'd', text: 'Epiretinal membrane' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm8q10', module: 'Retina', text: 'The photopigment found in rod cells, which is highly sensitive to light, is called:', options: [{ id: 'a', text: 'Photopsin' },{ id: 'b', text: 'Melanopsin' },{ id: 'c', text: 'Rhodopsin' },{ id: 'd', text: 'Opsin' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },

    // Module 9: Optic Nerve & Pathways (Total Points: 24)
    { id: 'm9q1', module: 'Optic Nerve & Pathways', text: 'The optic disc represents the anatomical location of the:', options: [{ id: 'a', text: 'Macula' },{ id: 'b', text: 'Fovea' },{ id: 'c', text: 'Physiological blind spot' },{ id: 'd', text: 'Ora serrata' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm9q2', module: 'Optic Nerve & Pathways', text: 'A patient presents with a loss of vision in the outer half of both visual fields (bitemporal hemianopia). This visual field defect is pathognomonic for a lesion at the:', options: [{ id: 'a', text: 'Optic nerve' },{ id: 'b', text: 'Optic chiasm' },{ id: 'c', text: 'Optic tract' },{ id: 'd', text: 'Visual cortex' }], correctAnswer: 'b', difficulty: 'hard', points: 5 },
    { id: 'm9q3', module: 'Optic Nerve & Pathways', text: 'The cup-to-disc ratio is a critical measurement used in the diagnosis and management of:', options: [{ id: 'a', text: 'Cataracts' },{ id: 'b', text: 'Macular degeneration' },{ id: 'c', text: 'Glaucoma' },{ id: 'd', text: 'Diabetic retinopathy' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm9q4', module: 'Optic Nerve & Pathways', text: 'Nerve fibers from the nasal half of the retina decussate (cross over) at the optic chiasm. Where do fibers from the temporal half of the retina go?', options: [{ id: 'a', text: 'They also decussate' },{ id: 'b', text: 'They travel down the ipsilateral (same side) optic tract' },{ id: 'c', text: 'They terminate at the chiasm' },{ id: 'd', text: 'They travel down the contralateral (opposite side) optic tract' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm9q5', module: 'Optic Nerve & Pathways', text: 'A right homonymous hemianopia with macular sparing is typically caused by an occlusion of which artery supplying the occipital lobe?', options: [{ id: 'a', text: 'Middle Cerebral Artery' },{ id: 'b', text: 'Anterior Cerebral Artery' },{ id: 'c', text: 'Posterior Cerebral Artery' },{ id: 'd', text: 'Basilar Artery' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm9q6', module: 'Optic Nerve & Pathways', text: 'Papilledema refers to bilateral optic disc swelling that is specifically caused by:', options: [{ id: 'a', text: 'High intraocular pressure (glaucoma)' },{ id: 'b', text: 'Inflammation of the optic nerve (optic neuritis)' },{ id: 'c', text: 'Ischemia (non-arteritic ischemic optic neuropathy)' },{ id: 'd', text: 'Increased intracranial pressure' }], correctAnswer: 'd', difficulty: 'medium', points: 2 },
    { id: 'm9q7', module: 'Optic Nerve & Pathways', text: 'Most of the axons in the optic tract synapse in which part of the thalamus?', options: [{ id: 'a', text: 'Medial Geniculate Nucleus' },{ id: 'b', text: 'Lateral Geniculate Nucleus (LGN)' },{ id: 'c', text: 'Pulvinar' },{ id: 'd', text: 'Superior Colliculus' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm9q8', module: 'Optic Nerve & Pathways', text: 'The characteristic pattern of visual field loss in early glaucoma often follows the:', options: [{ id: 'a', text: 'Horizontal meridian (altitudinal defect)' },{ id: 'b', text: 'Vertical meridian (hemianopic defect)' },{ id: 'c', text: 'Arcuate pattern of the retinal nerve fiber layer' },{ id: 'd', text: 'Random, scattered pattern of scotomas' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm9q9', module: 'Optic Nerve & Pathways', text: 'Optic neuritis, characterized by acute vision loss and pain on eye movement, is most commonly associated with which systemic demyelinating disease?', options: [{ id: 'a', text: 'Diabetes' },{ id: 'b', text: 'Multiple Sclerosis' },{ id: 'c', text: 'Hypertension' },{ id: 'd', text: 'Rheumatoid Arthritis' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },
    { id: 'm9q10', module: 'Optic Nerve & Pathways', text: 'A key feature that distinguishes a visual field defect caused by a post-chiasmal lesion from a retinal or optic nerve lesion is that it:', options: [{ id: 'a', text: 'Is always absolute' },{ id: 'b', text: 'Respects the vertical midline' },{ id: 'c', text: 'Respects the horizontal midline' },{ id: 'd', text: 'Is always relative' }], correctAnswer: 'b', difficulty: 'medium', points: 2 },

    // Module 10: Extraocular Muscles & Ocular Motility (Total Points: 16)
    { id: 'm10q1', module: 'Extraocular Muscles & Ocular Motility', text: 'Which muscle is primarily responsible for abduction (moving the eye outward, away from the nose)?', options: [{ id: 'a', text: 'Medial Rectus' },{ id: 'b', text: 'Lateral Rectus' },{ id: 'c', text: 'Superior Rectus' },{ id: 'd', text: 'Inferior Rectus' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm10q2', module: 'Extraocular Muscles & Ocular Motility', text: 'The superior oblique muscle is innervated by which cranial nerve?', options: [{ id: 'a', text: 'CN III (Oculomotor)' },{ id: 'b', text: 'CN IV (Trochlear)' },{ id: 'c', text: 'CN V (Trigeminal)' },{ id: 'd', text: 'CN VI (Abducens)' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },
    { id: 'm10q3', module: 'Extraocular Muscles & Ocular Motility', text: 'A patient is asked to look to their right. According to Hering\'s Law of Equal Innervation, which two muscles receive equal and simultaneous stimulation?', options: [{ id: 'a', text: 'Right Lateral Rectus and Left Lateral Rectus' },{ id: 'b', text: 'Right Medial Rectus and Left Lateral Rectus' },{ id: 'c', text: 'Right Lateral Rectus and Left Medial Rectus' },{ id: 'd', text: 'Right Superior Rectus and Left Inferior Oblique' }], correctAnswer: 'c', difficulty: 'hard', points: 5 },
    { id: 'm10q4', module: 'Extraocular Muscles & Ocular Motility', text: 'A "down and out" position of the eye at rest, along with ptosis and a dilated pupil, strongly suggests a palsy of which cranial nerve?', options: [{ id: 'a', text: 'CN III (Oculomotor)' },{ id: 'b', text: 'CN IV (Trochlear)' },{ id: 'c', text: 'CN VI (Abducens)' },{ id: 'd', text: 'CN VII (Facial)' }], correctAnswer: 'a', difficulty: 'medium', points: 2 },
    { id: 'm10q5', module: 'Extraocular Muscles & Ocular Motility', text: 'The primary action of the inferior oblique muscle is:', options: [{ id: 'a', text: 'Incyclotorsion' },{ id: 'b', text: 'Depression' },{ id: 'c', text: 'Abduction' },{ id: 'd', text: 'Excyclotorsion' }], correctAnswer: 'd', difficulty: 'medium', points: 2 },
    { id: 'm10q6', module: 'Extraocular Muscles & Ocular Motility', text: 'A patient reports vertical diplopia that worsens when they look down and to the left, and they tilt their head to the right to compensate. This is a classic presentation of a palsy of which muscle?', options: [{ id: 'a', text: 'Left Superior Rectus' },{ id: 'b', text: 'Right Inferior Rectus' },{ id: 'c', text: 'Right Superior Oblique' },{ id: 'd', text: 'Left Inferior Oblique' }], correctAnswer: 'c', difficulty: 'medium', points: 2 },
    { id: 'm10q7', module: 'Extraocular Muscles & Ocular Motility', text: 'Strabismus is the clinical term for:', options: [{ id: 'a', text: 'Lazy eye (amblyopia)' },{ id: 'b', text: 'Double vision (diplopia)' },{ id: 'c', text: 'Misalignment of the eyes' },{ id: 'd', text: 'Involuntary, rhythmic eye movements (nystagmus)' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm10q8', module: 'Extraocular Muscles & Ocular Motility', text: 'Which extraocular muscle originates from the orbital floor, not from the common tendinous ring (annulus of Zinn) at the orbital apex?', options: [{ id: 'a', text: 'Superior Rectus' },{ id: 'b', text: 'Medial Rectus' },{ id: 'c', text: 'Lateral Rectus' },{ id: 'd', text: 'Inferior Oblique' }], correctAnswer: 'd', difficulty: 'easy', points: 1 },
    { id: 'm10q9', module: 'Extraocular Muscles & Ocular Motility', text: 'The "H-pattern" motility test is designed to:', options: [{ id: 'a', text: 'Assess pupillary responses' },{ id: 'b', text: 'Measure intraocular pressure' },{ id: 'c', text: 'Isolate and test the primary action of each extraocular muscle in its diagnostic field of gaze' },{ id: 'd', text: 'Evaluate the visual field' }], correctAnswer: 'c', difficulty: 'easy', points: 1 },
    { id: 'm10q10', module: 'Extraocular Muscles & Ocular Motility', text: 'Sherrington\'s Law of Reciprocal Innervation states that when an agonist muscle contracts:', options: [{ id: 'a', text: 'Its contralateral yoke muscle also contracts' },{ id: 'b', text: 'Its ipsilateral (same eye) antagonist muscle relaxes' },{ id: 'c', text: 'Its ipsilateral antagonist muscle also contracts' },{ id: 'd', 'text': 'All other extraocular muscles relax' }], correctAnswer: 'b', difficulty: 'easy', points: 1 },

];
