
import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sparkles,
  User,
  FileText,
  MessageCircle,
  Send,
  Download,
  Image as ImageIcon,
  ArrowLeft,
  RefreshCw,
  Brain,
  HelpCircle,
  Stethoscope,
  GraduationCap,
  Target,
} from "lucide-react";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "./ui/table";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Label } from "./ui/label";
import { type GenerateCaseStudyOutput } from "@/ai/flows/generate-case-study";
import { toPng } from 'html-to-image';
import { useToast } from "@/hooks/use-toast";
import { DialogDescription, DialogHeader, DialogTitle } from "./ui/dialog";


function formatCaseStudyContent(markdown: string) {
  if (!markdown) return '';
  
  let html = markdown
    .replace(/^### (.*?$)/gm, '<h3 class="text-lg font-semibold text-slate-800 mt-4 mb-2">$1</h3>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');

  // Handle unordered lists (lines starting with - or *)
  html = html.replace(/^[-*] (.*?$)/gm, (match, content) => {
    return `<li class="flex items-start gap-2"><span class="mt-1.5 h-1.5 w-1.5 rounded-full bg-slate-400"></span><span>${content.trim()}</span></li>`;
  });

  // Handle ordered lists
  html = html.replace(/^\d+\.\s(.*?$)/gm, (match, content) => {
    const number = match.match(/^\d+/)?.[0];
    return `<li class="flex items-start gap-2"><span class="font-semibold text-slate-500">${number}.</span><span>${content.trim()}</span></li>`;
  });
  
  // Wrap list items in <ul> or <ol>
  html = html.replace(/(<li class="flex items-start gap-2"><span class="mt-1\.5.*<\/li>)/gs, (match) => {
    return `<ul class="list-none space-y-1 pl-2 my-4">${match}</ul>`;
  }).replace(/(<li class="flex items-start gap-2"><span class="font-semibold.*<\/li>)/gs, (match) => {
    return `<ol class="list-none space-y-1 pl-2 my-4">${match}</ol>`;
  });
  
  // Handle blockquotes
  html = html.replace(/^> (.*?$)/gm, '<div class="my-4 border-l-4 border-blue-500 bg-blue-50 text-blue-800 p-4 rounded-r-lg">$1</div>');
  
  // Handle tables
  const tableRegex = /(?:^\|.*\|(?:\r?\n|$))+/gm;
  html = html.replace(tableRegex, (table) => {
    const rows = table.trim().split(/\r?\n/).filter(row => row.trim());
    if (rows.length < 2) return table;

    const headerSeparator = rows[1];
    if (!headerSeparator.includes('|') || !headerSeparator.includes('-')) return table;

    const header = `<thead><tr class="m-0 border-t p-0 bg-slate-50">${rows[0].split('|').slice(1, -1).map(cell => `<th class="border px-4 py-2 text-left font-bold text-slate-700">${cell.trim()}</th>`).join('')}</tr></thead>`;
    
    const bodyRows = rows.slice(2);
    const body = `<tbody>${bodyRows.map(row => `<tr class="m-0 border-t p-0 even:bg-slate-50/50">${row.split('|').slice(1, -1).map(cell => `<td class="border px-4 py-2 text-left text-slate-600">${cell.trim()}</td>`).join('')}</tr>`).join('')}</tbody>`;

    return `<div class="my-6 overflow-x-auto rounded-lg border shadow-sm"><table class="w-full text-sm">${header}${body}</table></div>`;
  });

  // Handle paragraphs - this logic can be tricky and may need refinement
  // A simple approach is to wrap non-list, non-table, non-heading blocks in <p> tags
  html = html.split(/\r?\n\r?\n/).map(paragraph => {
      const trimmed = paragraph.trim();
      if (!trimmed) return '';
      if (trimmed.startsWith('<h3') || trimmed.startsWith('<ul') || trimmed.startsWith('<ol') || trimmed.startsWith('<div')) {
          return trimmed; // Don't wrap elements that are already block-level
      }
      return `<p>${trimmed}</p>`;
  }).join('');


  return html;
}


export function CaseSheet({ caseData, topic }: { caseData: GenerateCaseStudyOutput, topic: string }) {
  const caseSheetRef = useRef<HTMLDivElement>(null);
  const { toast } = useToast();
  
  const handleDownload = () => {
    if (caseSheetRef.current === null) {
      return;
    }
    toPng(caseSheetRef.current, { cacheBust: true, pixelRatio: 2 })
      .then((dataUrl) => {
        const link = document.createElement("a");
        link.download = `case-study-${topic.replace(/\s+/g, '-')}.png`;
        link.href = dataUrl;
        link.click();
      })
      .catch((err) => {
        console.error(err);
        toast({
            variant: "destructive",
            title: "Download Failed",
            description: "Could not generate an image of the case sheet."
        });
      });
  };

  return (
    <div>
        <div className="p-6 bg-slate-50 border-b">
             <DialogHeader>
              <DialogTitle className='sr-only'>AI Generated Case Study</DialogTitle>
              <DialogDescription className='sr-only'>A case study about {topic} generated by AI.</DialogDescription>
            </DialogHeader>
            <div className="flex justify-between items-center">
                <div>
                  <h2 className="text-2xl font-bold font-headline text-slate-800">{caseData.title}</h2>
                  <p className="text-sm text-muted-foreground">AI-Generated Case for: "{topic}"</p>
                </div>
                <Button onClick={handleDownload} variant="outline" size="sm">
                    <Download className="mr-2 h-4 w-4" />
                    Download
                </Button>
            </div>
        </div>
        <div className="max-h-[70vh] overflow-y-auto">
            <div ref={caseSheetRef} className="p-8 bg-white">
                <section className="mb-6">
                    <h3 className="text-xl font-bold text-slate-800 border-b-2 border-primary pb-2 mb-4 flex items-center gap-2"><User className="h-5 w-5 text-primary"/> Patient Presentation</h3>
                    <p className="text-slate-600 leading-relaxed">{caseData.patientPresentation}</p>
                </section>
                <section className="mb-6">
                    <h3 className="text-xl font-bold text-slate-800 border-b-2 border-primary pb-2 mb-4 flex items-center gap-2"><Stethoscope className="h-5 w-5 text-primary"/> Examination Findings</h3>
                    <div className="prose max-w-none" dangerouslySetInnerHTML={{ __html: formatCaseStudyContent(caseData.examinationFindings) }} />
                </section>
                <section className="mb-6">
                    <h3 className="text-xl font-bold text-slate-800 border-b-2 border-primary pb-2 mb-4 flex items-center gap-2"><GraduationCap className="h-5 w-5 text-primary"/> Diagnosis</h3>
                    <div className="bg-amber-50 border-l-4 border-amber-500 p-4 rounded-r-lg">
                        <p className="font-semibold text-amber-800">{caseData.diagnosis}</p>
                    </div>
                </section>
                <section>
                    <h3 className="text-xl font-bold text-slate-800 border-b-2 border-primary pb-2 mb-4 flex items-center gap-2"><Brain className="h-5 w-5 text-primary"/> Clinical Discussion</h3>
                    <div className="prose max-w-none text-slate-600" dangerouslySetInnerHTML={{ __html: formatCaseStudyContent(caseData.clinicalDiscussion) }} />
                </section>
            </div>
        </div>
        <div className="p-3 text-center bg-slate-800 text-slate-300 text-xs rounded-b-lg">
            AI-generated for educational purposes only. Always verify with clinical sources.
        </div>
    </div>
  );
}
